use NASSCROP;

delete from crop;

LOAD DATA local infile 'crops.txt'
INTO TABLE crop
fields terminated BY "\t"
lines terminated BY "\n"
ignore 1 lines
(SOURCE_DESC, SECTOR_DESC, GROUP_DESC, COMMODITY_DESC, CLASS_DESC, PRODN_PRACTICE_DESC, UTIL_PRACTICE_DESC, STATISTICCAT_DESC, UNIT_DESC, SHORT_DESC, DOMAIN_DESC, DOMAINCAT_DESC, AGG_LEVEL_DESC, STATE_ANSI, STATE_FIPS_CODE, STATE_ALPHA, STATE_NAME, ASD_CODE, ASD_DESC, COUNTY_ANSI, COUNTY_CODE, COUNTY_NAME, REGION_DESC, ZIP_5, WATERSHED_CODE, WATERSHED_DESC, CONGR_DISTRICT_CODE, COUNTRY_CODE, COUNTRY_NAME, LOCATION_DESC, YEAR, FREQ_DESC, BEGIN_CODE, END_CODE, REFERENCE_PERIOD_DESC, WEEK_ENDING, LOAD_TIME, VALUE, CV);

