use NASSCROP;

SELECT 'YEAR', 'COMMODITY_DESC', 'STATISTICCAT_DESC', 'STATE_FIPS_CODE', 'STATE_NAME', 'COUNTRY_CODE', 'COUNTRY_NAME', 'LOCATION_DESC', 'VALUE'
UNION ALL
select YEAR, COMMODITY_DESC, STATISTICCAT_DESC, STATE_FIPS_CODE, STATE_NAME, COUNTRY_CODE, COUNTRY_NAME, LOCATION_DESC, VALUE
from crop where COMMODITY_DESC like "%CORN%"
INTO OUTFILE 'CORN.tsv';

SELECT 'YEAR', 'COMMODITY_DESC', 'STATISTICCAT_DESC', 'STATE_FIPS_CODE', 'STATE_NAME', 'COUNTRY_CODE', 'COUNTRY_NAME', 'LOCATION_DESC', 'VALUE'
UNION ALL
select YEAR, COMMODITY_DESC, STATISTICCAT_DESC, STATE_FIPS_CODE, STATE_NAME, COUNTRY_CODE, COUNTRY_NAME, LOCATION_DESC, VALUE
from crop where COMMODITY_DESC like "%RICE%"
INTO OUTFILE 'RICE.tsv';

SELECT 'YEAR', 'COMMODITY_DESC', 'STATISTICCAT_DESC', 'STATE_FIPS_CODE', 'STATE_NAME', 'COUNTRY_CODE', 'COUNTRY_NAME', 'LOCATION_DESC', 'VALUE'
UNION ALL
select YEAR, COMMODITY_DESC, STATISTICCAT_DESC, STATE_FIPS_CODE, STATE_NAME, COUNTRY_CODE, COUNTRY_NAME, LOCATION_DESC, VALUE
from crop where COMMODITY_DESC  like "%SOYBEANS%"
INTO OUTFILE 'SOYBEANS.tsv';

SELECT 'YEAR', 'COMMODITY_DESC', 'STATISTICCAT_DESC', 'STATE_FIPS_CODE', 'STATE_NAME', 'COUNTRY_CODE', 'COUNTRY_NAME', 'LOCATION_DESC', 'VALUE'
UNION ALL
select YEAR, COMMODITY_DESC, STATISTICCAT_DESC, STATE_FIPS_CODE, STATE_NAME, COUNTRY_CODE, COUNTRY_NAME, LOCATION_DESC, VALUE
from crop where COMMODITY_DESC like "WHEAT"
INTO OUTFILE 'WHEAT.tsv';


